#ifndef PREGUNTAS_H
#define PREGUNTAS_H
char* pregunta1();
char* pregunta2();
char* pregunta3();
char* pregunta4();
char* pregunta5();
char* pregunta6();
char* pregunta7();
char* pregunta8();
char* pregunta9();
char* pregunta10();
char* pregunta11();
char* pregunta12();
char* pregunta13();
char* pregunta14();
char* pregunta15();
char* pregunta16();
char* pregunta17();
char* pregunta18();
char* pregunta19();
char* pregunta20();
char* pregunta21();
char* pregunta22();
char* pregunta23();
char* pregunta24();
char* pregunta25();
char* pregunta26();
#endif
